/**
 * Superagent — Wallet Setup Script
 * Generates 3 Stellar testnet keypairs and funds them via Friendbot
 * Run: npm run setup
 * Optional: node src/setup-wallets.js --show-secrets
 */

import { Keypair } from '@stellar/stellar-sdk'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SHOW_FULL_SECRETS = process.argv.includes('--show-secrets')

function maskSecret(secret) {
  if (!secret || secret.length < 10) return '***'
  return `${secret.slice(0, 4)}...${secret.slice(-4)}`
}

async function fundWithFriendbot(publicKey, label) {
  try {
    console.log(`  Funding ${label} (${publicKey.slice(0, 8)}...)...`)
    const res = await fetch(`https://friendbot.stellar.org?addr=${publicKey}`)
    if (res.ok) {
      console.log(`  ✅ ${label} funded with 10,000 XLM`)
      return true
    } else {
      const text = await res.text()
      // Account may already exist
      if (text.includes('createAccountAlreadyExist')) {
        console.log(`  ℹ️  ${label} already exists and is funded`)
        return true
      }
      console.error(`  ❌ ${label} funding failed:`, text.slice(0, 100))
      return false
    }
  } catch (err) {
    console.error(`  ❌ ${label} funding error:`, err.message)
    return false
  }
}

async function main() {
  console.log(`
╔══════════════════════════════════════════════════╗
║       🧠 Superagent — Wallet Setup              ║
║       Generating 3 Stellar Testnet Wallets        ║
╚══════════════════════════════════════════════════╝
  `)

  // Generate 3 keypairs
  const server = Keypair.random()
  const orchestrator = Keypair.random()
  const buyer = Keypair.random()

  console.log('📋 Generated Keypairs:\n')
  if (!SHOW_FULL_SECRETS) {
    console.log(
      '  🔒 Secret keys are masked by default. Use --show-secrets to print full secrets.\n'
    )
  }
  console.log(`  SERVER (receives agent payments):`)
  console.log(`    Public:  ${server.publicKey()}`)
  console.log(`    Secret:  ${SHOW_FULL_SECRETS ? server.secret() : maskSecret(server.secret())}\n`)

  console.log(`  ORCHESTRATOR (pays for sub-agent calls):`)
  console.log(`    Public:  ${orchestrator.publicKey()}`)
  console.log(
    `    Secret:  ${SHOW_FULL_SECRETS ? orchestrator.secret() : maskSecret(orchestrator.secret())}\n`
  )

  console.log(`  BUYER (demo user wallet):`)
  console.log(`    Public:  ${buyer.publicKey()}`)
  console.log(`    Secret:  ${SHOW_FULL_SECRETS ? buyer.secret() : maskSecret(buyer.secret())}\n`)

  // Fund all 3 via Friendbot
  console.log('💰 Funding wallets via Friendbot...\n')
  await fundWithFriendbot(server.publicKey(), 'Server')
  await fundWithFriendbot(orchestrator.publicKey(), 'Orchestrator')
  await fundWithFriendbot(buyer.publicKey(), 'Buyer')

  // Generate .env file
  const envContent = `# Superagent — Auto-generated by setup script
# Generated at: ${new Date().toISOString()}

# Server wallet — receives payments for agent services
SERVER_STELLAR_ADDRESS=${server.publicKey()}
SERVER_STELLAR_SECRET=${server.secret()}

# Orchestrator agent wallet — pays for services on behalf of users
ORCHESTRATOR_STELLAR_ADDRESS=${orchestrator.publicKey()}
ORCHESTRATOR_STELLAR_SECRET=${orchestrator.secret()}

# Buyer agent wallet — end-user demo wallet
BUYER_STELLAR_ADDRESS=${buyer.publicKey()}
BUYER_STELLAR_SECRET=${buyer.secret()}

# Anthropic API Key — get from https://console.anthropic.com
ANTHROPIC_API_KEY=

# Network config
NETWORK=stellar:testnet
FACILITATOR_URL=https://www.x402.org/facilitator
STELLAR_RPC_URL=https://soroban-testnet.stellar.org

# Server
PORT=3001
`

  const envPath = path.join(__dirname, '..', '.env')

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    console.log('\n⚠️  .env file already exists!')
    console.log('   Saving new config to .env.generated instead.')
    fs.writeFileSync(envPath + '.generated', envContent)
    console.log(`   Written to: ${envPath}.generated`)
  } else {
    fs.writeFileSync(envPath, envContent)
    console.log(`\n✅ .env file created at: ${envPath}`)
  }

  console.log(`
╔══════════════════════════════════════════════════╗
║  ✅ Setup Complete!                               ║
╠══════════════════════════════════════════════════╣
║                                                  ║
║  Next steps:                                     ║
║  1. Add your ANTHROPIC_API_KEY to .env           ║
║     Get one at: https://console.anthropic.com    ║
║                                                  ║
║  2. (Optional) Get testnet USDC:                 ║
║     - Create USDC trustline at lab.stellar.org   ║
║     - Get USDC from faucet.circle.com            ║
║                                                  ║
║  3. Start the server:                            ║
║     npm run dev                                  ║
║                                                  ║
║  4. Open dashboard at http://localhost:3001       ║
║                                                  ║
╚══════════════════════════════════════════════════╝

  Verify wallets on Stellar Expert:
  https://stellar.expert/explorer/testnet/account/${server.publicKey()}
  https://stellar.expert/explorer/testnet/account/${orchestrator.publicKey()}
  https://stellar.expert/explorer/testnet/account/${buyer.publicKey()}
  `)
}

main().catch((err) => {
  console.error('Setup failed:', err)
  process.exit(1)
})
